### GENERAL SETTINGS ###

# Site settings
title: © 哨兵
brand: SENTINEL SECURITY, LAB
description: 哨兵安全实验室
baseurl: "" #important: start with /
url: "https://bin4xin.sentrylab.cn"
root: "sentrylab.cn"
web_version: V2.3
www_google_verify: "apz36MBrhPsyyKahn-qJWKDq0PQUASdgn5_nju0NwQE"
timezone: Asia/Shanghai #set timezone to display build time correctly
highlighter: rouge
markdown: kramdown
PicturesLinks_Domain: //image.yjs2635.xyz
kramdown:
    input: GFM
    hard_wrap: false

permalink: "/:categories/:year/:title/"

excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
# TODO plugins: ["jekyll-toc", "jekyll-roman", "jekyll-paginate"]
# paginate: 5
# paginate_path: "/blog/page:num/"
plugins: ["jekyll-toc", "jekyll-roman"]
#--[toc plugin], while run jekyll to build sites, jekyll-toc could define some to display:
#--the toc class
#--the toc min/max level
toc:
  item_class: no-underline table-of-contents Item__StyledItem-sc-yeql7o-2 edSFyN flex-column # Default: "toc-entry"
  min_level: 1 # default: 1
  max_level: 4 # default: 6

sass:
    sass_dir: assets/css
future: true
meow_404: true

include: ['_pages','_primaryindex']
exclude: ['BUILD.md', 'README.md','vendor']

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "本站由哨兵安全实验室支持创办"

jekyll-archives:
  layouts:
    categories: categories
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

contactMail: "administrator@sentrylab.cn"
# option.
githubAccess: "https://github.com/Bin4xin"
githubRepos: "bin4xin.github.io"
# repos:
githubIO: "https://bin4xin.github.io"
githubRepos-Branch: "main"
# Build commit hash strings settings
#harmony: 国家公祭日
#harmonyURL: http://www.cngongji.cn
