name: build sync and reload

on:
  push: 
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Cache Ruby Bundler
      id: cache
      uses: actions/cache@v2
      env:
        CACHE_ID: 1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-
    #- name: Change rubygems loading
    #  run: sed -i "/^source/c source 'https://rubygems.org'" Gemfile
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: bundle install --jobs=4 --retry=3
    - name: setup commit hash string
      run: commitString=$(git rev-parse HEAD) && echo "commitString: $commitString" >> _config.yml
    - name: Run jekyll-build
      run: bundle config set --local path 'vendor/bundle' && bundle exec jekyll build --trace
    - name: Simple deploy with git
      uses: rdarida/simple-github-pages-deploy-action@v1
      with: # optional
        git-user: ${{ secrets.Git_USERNAME }}
        git-email: ${{ secrets.Git_EMAIL }}
        git-base-folder: '_site'
        commit-message: '<auto generate>: page build/deploy by github action.'
        branch: 'gh-pages'
  # sync start
  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:Bin4xin/bin4xin.github.io.git"
        # 目标仓库
        destination-repo: "git@gitee.com:bin4xin/bin4xin.git"
  # reload-pages:
  #   needs: sync
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build Gitee Pages
  #       uses: yanglbme/gitee-pages-action@main
  #       with:
  #         # 注意替换为你的 Gitee 用户名
  #         gitee-username: ${{ secrets.GIT_USERNAME}}
  #         # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
  #         gitee-password: ${{ secrets.GITEE_PASSWORD }}
  #         # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
  #         gitee-repo: 'bin4xin/bin4xin'
  # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
  #         branch: 'gh_pages'
  gitee-check-rebuild:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: rebuild-GiteePro
        run: curl -H "${{ secrets.GITEE_CRSFTOKEN }}" -b "${{ secrets.GITEE_TOKEN }}" -d "branch=gh-pages&build_directory=&force_https=true&auto_update=true"  https://gitee.com/${{ secrets.GIT_USERNAME }}/${{ secrets.GIT_USERNAME }}/pages/rebuild